set nocompatible
filetype plugin indent on
syntax on

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

set autoindent
set autoread
set backspace=indent,eol,start
set display=lastline
set encoding=utf-8
set formatoptions+=j
set history=200
set incsearch
set laststatus=2
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
set nrformats-=octal
set ruler
set scrolloff=2
set sessionoptions-=options
set showcmd
set smarttab
set tabpagemax=50
set ttimeout
set ttimeoutlen=100
set viewoptions-=options
set viminfo^=!
set wildmenu

set backupdir=~/.vim/tmp/
set directory=~/.vim/tmp/
set undodir=~/.vim/tmp/
set viminfo+=n~/.vim/.viminfo

noremap Q <nop>
